### ISSUE TITLE
Data Serialization Format

### ISSUE THREAD

**Issue by eak24** [AguaClara/aide_tutorial#14]
I've done some thinking and experimenting, hunting for the best data serialization format to use to persistently store plant related parameters. My evaluation focused on:

1. Community support
2. Readability
3. Supported functionality

The first priority, community support, narrowed it down to JSON, YAML and XML. Initially, I adopted JSON, as JSON is the most popular human-readable format available. After playing with JSON path creation and resolution, and looking at JSON's serialization limitations, I've come to the conclusion that tags and anchors within YAML far outweigh JSON's popularity edge. 

YAML is a superset of JSON, therefore any JSON string/ file IS a valid YAML file.

YAML is more human readable and has similarly whitespace-dependent syntax as Python. 

Quick comparison of the two:

JSON:
{
  "add":[
    {"multiply": [5, 2, 5]},
    4
  ]
}

YAML:
add:
    - {multiply: [5, 2, 5]}
    - 4

Loading and dumping will be done with pyYaml.

I don't think this has much of an impact on any of the teams right now - the only change would be for aide_document, but that is a one-line change from json.load() to yaml.load()

I'd be delighted to hear any additional thoughts on this on the issue I made here!

**Comment by oliver-leung** [comment]
YAML has ascended the throne as AIDE's preferred data serialization format!
